# Generated by Django 5.1.1 on 2025-06-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservationlot_reserve_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationlot',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
