# Generated by Django 5.1.1 on 2025-09-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservationlot_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlot',
            name='reserve_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservationlot',
            name='soft_delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationlot',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
