# Generated by Django 5.1.1 on 2025-09-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_fix_soft_delete_constraint'),
        ('reservation', '0004_alter_reservationlot_reserve_date_and_more'),
    ]

    operations = [
    ]
