# Generated by Django 5.1.1 on 2025-09-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_recreate_reservationlot_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlot',
            name='soft_delete',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
